// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkmrywvdtvhsdbgfjuqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbXJ5d3ZkdHZoc2RiZ2ZqdXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2ODA5NDIsImV4cCI6MjA4NjI1Njk0Mn0.gzRagfhrm6kqtyCVTW2o-f6UXa5ejqVL6TisDHpBWvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});